#!/bin/bash

#SBATCH --job-name=mkref_A4
#SBATCH -A JRANZ_LAB
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8G
#SBATCH --error=%x.%A.err
#SBATCH --output=%x.%A.out

# Load Parse split-pipe environment
module load anaconda
source activate spipe

# Run mkref to create Parse-compatible reference for A4
split-pipe --mode mkref \
  --genome_name A4_GCA_003401745.1_ASM340174v1 \
  --fasta /pub/ihariyan/ranz_lab/data/genome/drosophila_melanogaster/A4/GCA_003401745.1_ASM340174v1_genomic.fa \
  --genes /pub/ihariyan/ranz_lab/data/genome/drosophila_melanogaster/A4/A4_ISO1-BDGP6.46/A4_GCA_003401745.1_ASM340174v1.protein_coding.gtf \
  --output_dir A4_GCA_003401745.1_ASM340174v1
