#!/bin/bash

#SBATCH --job-name=filter-gtf
#SBATCH -A JRANZ_LAB
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=30G
#SBATCH --error=%x.%A.err
#SBATCH --output=%x.%A.out

# Load Cell Ranger module
module load cellranger

# Extract only protein-coding genes from the GTF
cellranger mkgtf \
  A4_GCA_003401745.1_ASM340174v1.gtf \
  A4_GCA_003401745.1_ASM340174v1.protein_coding.gtf \
  --attribute=gene_biotype:protein_coding
