#!/bin/bash

#SBATCH --job-name=liftoff
#SBATCH -A JRANZ_LAB
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=12G
#SBATCH --error=%x.%A.err
#SBATCH --output=%x.%A.out

# Load Liftoff environment
module load anaconda
source activate Liftoff

# Run Liftoff to map ISO1 GTF to A4 genome
liftoff \
  -g Drosophila_melanogaster.BDGP6.46.111.gtf.gz \
  -o A4_GCA_003401745.1_ASM340174v1.gtf \
  A4_GCA_003401745.1_ASM340174v1.fa \
  Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa
