#!/bin/bash

#SBATCH --job-name=mkref_ISO1
#SBATCH -A JRANZ_LAB
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8G
#SBATCH --error=%x.%A.err
#SBATCH --output=%x.%A.out

# Load Parse split-pipe environment
module load anaconda
source activate spipe

# Run mkref to create Parse-compatible reference for ISO1
split-pipe --mode mkref \
  --genome_name ISO1_BDGP6.46 \
  --fasta /pub/ihariyan/ranz_lab/data/genome/drosophila_melanogaster/ISO1/Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa \
  --genes /pub/ihariyan/ranz_lab/data/genome/drosophila_melanogaster/ISO1/Drosophila_melanogaster.BDGP6.46.111.protein_coding.gtf \
  --output_dir ISO1_BDGP6.46
