#!/bin/bash

#SBATCH --job-name=mkref_w501
#SBATCH -A JRANZ_LAB
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8G
#SBATCH --error=%x.%A.err
#SBATCH --output=%x.%A.out

# Load Parse split-pipe environment
module load anaconda
source activate spipe

# Run mkref to create Parse-compatible reference for w501
split-pipe --mode mkref \
  --genome_name w501_ASM75419v3.58 \
  --fasta /pub/ihariyan/ranz_lab/data/genome/drosophila_simulans/w501_ASM75419v3.58/Drosophila_simulans.ASM75419v3.dna.toplevel.fa.gz \
  --genes /pub/ihariyan/ranz_lab/data/genome/drosophila_simulans/w501_ASM75419v3.58/Drosophila_simulans.ASM75419v3.58.protein_coding.gtf \
  --output_dir w501_ASM75419v3.58_ref
